<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>ScoreMarker.Setup</AssemblyName>
    <RootNamespace>ScoreMarker.Setup</RootNamespace>
    <ApplicationIcon>..\assets\app.ico</ApplicationIcon>
    <AssemblyTitle>智能批分助手安装器</AssemblyTitle>
    <Product>智能批分助手安装器</Product>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="package\app.zip" />
  </ItemGroup>
</Project>
